version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: goyo-localhost-postgresql-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: postgres
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

volumes:
  postgresql-volume:
