export enum ErrorCode {
  DUPLICATED_EMAIL = 'DUPLICATED_EMAIL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  REFRESH_TOKEN_REQUIRED = 'REFRESH_TOKEN_REQUIRED',
}
